import type { CampaignRecord } from "./types";

export const SEED_CAMPAIGNS: CampaignRecord[] = [
  {
    id: "cmp_niche_01",
    slug: "meridian-labs-locked-in",
    title: "Locked In",
    brand: "Meridian Labs",
    tagline: "Early mornings. Compound wins. The rest follows.",
    brief:
      "For creators running a high-agency, self-improvement page (Gen Z men, 16–28). Two Reels: one morning-routine montage, one book-and-barbell voiceover framed around 'high agency' as a personality trait. We license for 60 days across Meridian's channels. Chris Williamson / Bryan Johnson / David Goggins energy welcomed.",
    payoutCents: 120000,
    currency: "USD",
    deadline: "2026-06-08",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "ink",
    createdAt: "2026-04-22T09:00:00.000Z",
  },
  {
    id: "cmp_niche_02",
    slug: "lune-co-peace-protected",
    title: "Peace, Protected",
    brand: "Lune & Co",
    tagline: "Slow mornings, kept sacred.",
    brief:
      "Soft-girl / feminine-energy lifestyle pages. One aesthetic b-roll Reel (matcha, pilates, journaling, linen) and one carousel post with 'delusional affirmations' or romanticize-the-mundane copy. Pinterest-core, clean-girl, quiet luxury. Audience: 18–30F.",
    payoutCents: 75000,
    currency: "USD",
    deadline: "2026-05-28",
    deliverables: [
      { kind: "reel", count: 1 },
      { kind: "post", count: 1 },
    ],
    status: "open",
    coverTone: "vermillion",
    createdAt: "2026-04-22T10:15:00.000Z",
  },
  {
    id: "cmp_niche_03",
    slug: "cadence-ai-ten-times",
    title: "Ten Times Before Noon",
    brand: "Cadence AI",
    tagline: "Ship more, think cleaner — with the stack.",
    brief:
      "AI power-user pages — knowledge workers, 22–40. Two Reels: one 'tool of the week' walkthrough and one 'things AI shipped for me this week' storytime. Claude / GPT-5 / Sora / agent workflow references fair game. We provide talking points and a discount code.",
    payoutCents: 150000,
    currency: "USD",
    deadline: "2026-06-02",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "ink",
    createdAt: "2026-04-22T11:00:00.000Z",
  },
  {
    id: "cmp_niche_04",
    slug: "dial-up-club-then-vs-now",
    title: "Then vs. Now",
    brand: "Dial-Up Club",
    tagline: "We grew up online. Now we grew up.",
    brief:
      "Late-millennial / geriatric-Gen-Z nostalgia pages (28–38). One Reel: Limewire / MSN / early-2000s internet screenshots vs. present-day adulthood. One carousel post: 'remember who you are' framing. Purchasing-power demographic — treat it with warmth, not cringe.",
    payoutCents: 85000,
    currency: "USD",
    deadline: "2026-06-12",
    deliverables: [
      { kind: "reel", count: 1 },
      { kind: "post", count: 1 },
    ],
    status: "open",
    coverTone: "ochre",
    createdAt: "2026-04-22T12:30:00.000Z",
  },
  {
    id: "cmp_niche_05",
    slug: "barbell-standard-iron-discipline",
    title: "Iron Discipline",
    brand: "Barbell Standard",
    tagline: "Heavy weights. Clean plates. No cope.",
    brief:
      "Serious-lifter fitness pages (16–30M). Two Reels: one physique-edit / gym-session montage, one training-split infographic walkthrough. Sam Sulek / protein-maxxing / carnivore-adjacent culture welcomed, within our brand guidelines. Supplement code + 60-day license.",
    payoutCents: 90000,
    currency: "USD",
    deadline: "2026-06-05",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "vermillion",
    createdAt: "2026-04-22T14:00:00.000Z",
  },
  {
    id: "cmp_niche_06",
    slug: "ticker-co-chart-monday",
    title: "Chart Monday",
    brand: "Ticker & Co",
    tagline: "Markets, moves, and the occasional flex.",
    brief:
      "Finance / markets commentary pages (22–35M). One Reel: a 'chart of the week' walkthrough tied to a live market story. Two Stories: earnings-season reactions or prediction-market hot takes. NVIDIA / AI-bubble / private-credit takes encouraged. High-net-worth audience — deliver substance, not just flex.",
    payoutCents: 140000,
    currency: "USD",
    deadline: "2026-06-01",
    deliverables: [
      { kind: "reel", count: 1 },
      { kind: "story", count: 2 },
    ],
    status: "open",
    coverTone: "forest",
    createdAt: "2026-04-22T15:00:00.000Z",
  },
  {
    id: "cmp_niche_07",
    slug: "signal-desk-sixty-seconds",
    title: "Sixty Seconds Abroad",
    brand: "Signal Desk",
    tagline: "The world, in plain language.",
    brief:
      "Geopolitics / global-affairs explainer pages (20–40). Two Reels: one map-based 'what's happening in [country]' explainer and one historical-parallel carousel-style reel. Neutral tone. No hot takes on live conflicts — educate, don't incite.",
    payoutCents: 95000,
    currency: "USD",
    deadline: "2026-06-10",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "ochre",
    createdAt: "2026-04-22T16:00:00.000Z",
  },
  {
    id: "cmp_niche_08",
    slug: "noir-femme-unbothered",
    title: "Unbothered",
    brand: "Noir Femme",
    tagline: "High standards, quiet presence.",
    brief:
      "Dark-feminine / 'that girl' pages (20–35F). One Reel: a 'signs you're unbothered' or 'high-value woman' framing, luxury-lifestyle-adjacent. One carousel post: psychology or dating-dynamics screenshots. Audience buys coaching / courses.",
    payoutCents: 90000,
    currency: "USD",
    deadline: "2026-05-30",
    deliverables: [
      { kind: "reel", count: 1 },
      { kind: "post", count: 1 },
    ],
    status: "open",
    coverTone: "ink",
    createdAt: "2026-04-23T09:00:00.000Z",
  },
  {
    id: "cmp_niche_09",
    slug: "zeitgeist-archive-commentary",
    title: "The Commentary",
    brand: "Zeitgeist Archive",
    tagline: "Reading the room. Screenshotting the times.",
    brief:
      "Cultural-commentary / meme-curation pages. Two Reels curating internet-culture screenshots with a 'man in the arena' framing — reflective, not reactionary. We vet all copy before publish; keep it cultural, not political. High-engagement audience.",
    payoutCents: 70000,
    currency: "USD",
    deadline: "2026-06-14",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "ink",
    createdAt: "2026-04-23T10:00:00.000Z",
  },
  {
    id: "cmp_niche_10",
    slug: "shipyard-build-in-public",
    title: "Build in Public",
    brand: "Shipyard",
    tagline: "Revenue. Reps. Receipts.",
    brief:
      "Startup-founder / indie-hacker pages (22–40). Two Reels: one 'tools I use to ship faster' walkthrough and one revenue-milestone screenshot reel. Vibe-coding / YC / Anthropic-OpenAI discourse all fair. Direct SaaS-buyer audience — substantive content wins.",
    payoutCents: 130000,
    currency: "USD",
    deadline: "2026-06-06",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "forest",
    createdAt: "2026-04-23T11:00:00.000Z",
  },
  {
    id: "cmp_niche_11",
    slug: "atelier-luxe-quiet-luxury",
    title: "Quiet Luxury",
    brand: "Atelier Luxe",
    tagline: "What you're actually working for.",
    brief:
      "Aspirational-wealth / luxury-lifestyle pages (18–35). One Reel: supercar, watch, or mansion walkthrough — Saltburn-aesthetic, not bling. One carousel post: 'a day in Monaco' style edit. Monetize via affiliate codes; audience converts on aspiration.",
    payoutCents: 160000,
    currency: "USD",
    deadline: "2026-06-20",
    deliverables: [
      { kind: "reel", count: 1 },
      { kind: "post", count: 1 },
    ],
    status: "open",
    coverTone: "ochre",
    createdAt: "2026-04-23T12:00:00.000Z",
  },
  {
    id: "cmp_niche_12",
    slug: "feed-daily-already-happened",
    title: "Today, Already Happened",
    brand: "Feed Daily",
    tagline: "You scroll. We curate. Drama, explained.",
    brief:
      "Chronically-online pop-culture pages (16–30F). One Reel: a drama-timeline or celebrity-breakup recap. One Story: hot takes with tweet compilations. Euphoria / Coachella / TikToker drama fair game. High engagement, fast turnaround.",
    payoutCents: 70000,
    currency: "USD",
    deadline: "2026-05-28",
    deliverables: [
      { kind: "reel", count: 1 },
      { kind: "story", count: 1 },
    ],
    status: "open",
    coverTone: "vermillion",
    createdAt: "2026-04-23T13:00:00.000Z",
  },
  {
    id: "cmp_niche_13",
    slug: "shadow-club-quiet-ones",
    title: "The Quiet Ones",
    brand: "Shadow Club",
    tagline: "Discipline without an audience.",
    brief:
      "Sigma / lone-wolf masculine-philosophy pages (14–25M). Two Reels: movie-edit compilations (Bateman / Shelby / Drive aesthetic) paired with stoicism quotes. 'Delete Instagram, read books' framing. Young audience — emphasize books and discipline over product push.",
    payoutCents: 65000,
    currency: "USD",
    deadline: "2026-06-10",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "ink",
    createdAt: "2026-04-23T14:00:00.000Z",
  },
  {
    id: "cmp_niche_14",
    slug: "high-vibration-regulated",
    title: "Nervous System, Regulated",
    brand: "High Vibration",
    tagline: "Root cause. Slow medicine. Real healing.",
    brief:
      "Conscious / spiritual-wellness pages (20–40F). One Reel: 'signs the universe is guiding you' or somatic-healing framing. One carousel post: journaling prompts or cycle-syncing infographic. Manifestation / nervous-system / root-cause-health content. Course-buying audience.",
    payoutCents: 90000,
    currency: "USD",
    deadline: "2026-06-04",
    deliverables: [
      { kind: "reel", count: 1 },
      { kind: "post", count: 1 },
    ],
    status: "open",
    coverTone: "vermillion",
    createdAt: "2026-04-23T15:00:00.000Z",
  },
  {
    id: "cmp_niche_15",
    slug: "hand-ink-analog-revival",
    title: "Analog Revival",
    brand: "Hand & Ink",
    tagline: "Made by people. On purpose.",
    brief:
      "Anti-AI / human-craft counter-trend pages (25–40). Two Reels: one artisan-process / film-photography / handmade-resurgence piece, one 'spot the AI' or 'before vs after AI ruined it' commentary. Educated, higher-income audience — less competition.",
    payoutCents: 110000,
    currency: "USD",
    deadline: "2026-06-16",
    deliverables: [{ kind: "reel", count: 2 }],
    status: "open",
    coverTone: "ochre",
    createdAt: "2026-04-23T16:00:00.000Z",
  },
];

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 60);
}
